### PR TITLE
Expand TLD validation size to 63 for long gTLD.

### PR DESCRIPTION
**Pull request by kevpie**
Newer live TLD's are already at 24 char and could grow all the way to 63 char.

### CODE REVIEW

**Comment by kevpie** [comment]
Hello @dresende, 
This solves an issue that came up with using one of the newer TLD's.  I had a user trying to register an like `user@some.college` from the `college` TLD.  I am using 3.2.0 of node-orm2 and hope to see this work it's way through soon.

Anything you would like changed? 

Thank you.

**Comment by dresende** [comment]
LGTM :)

**Comment by dresende** [comment]
https://github.com/dresende/node-orm2/pull/763

**Comment by dxg** [comment]
Released in version 3.2.3

**Pull request merged**
